### ISSUE TITLE
createOSMStream only works with nodes and not ways or relations

### ISSUE THREAD

**Issue by amankkg** [borisgontar/osm-pbf-parser-node#2]
I tried to parse `berlin.osm.pbf` with the snippet given in the readme, and it seems like it can't parse objects other than `type="node"`.

Double-checking with `osmium` cli app, there are definitely some ways and relations present in the pbf file.

**Comment by borisgontar** [comment]
Works for me in 1.1.4, please update and try again.

**Comment by amankkg** [comment]
It works as expected now, thanks!
